name: discipulus
description: "Gelukkig geen onderdeel van Magister 🙌"
publish_to: 'none'
version: 0.1.4+16

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Core
  animations: ^2.0.8
  collection: ^1.18.0
  dynamic_color: ^1.7.0
  pointycastle: ^3.7.3
  url_launcher: ^6.1.14
  mime: ^1.0.5
  intl: ^0.19.0
  isar: ^3.1.0+1
  path_provider: ^2.1.1
  cross_file: ^0.3.3+6
  dio: ^5.3.3
  isar_flutter_libs: ^3.1.0+1
  flutter:
    sdk: flutter

  # Firebase 
  # 
  #   For sme reason this breaks macOS completely, so for now it is not included.
  #   firebase_messaging: ^15.1.3
  #   firebase_core: ^3.6.0 
 
  # Widgets
  fl_chart: ^0.69.0
  flutter_adaptive_scaffold: ^0.2.6
  flutter_advanced_drawer: 
    path: packages/flutter_advanced_drawer/
  fleather: 
    git:
      url: https://github.com/fleather-editor/fleather.git
      path: packages/fleather
      ref: c391628324db2bf1ba831aa7f990a3967e361dca
  infinite_scroll_pagination: ^4.0.0
  focus_on_it: ^2.0.1

  # HTML & Other parsers
  flutter_html: ^3.0.0-beta.2
  flutter_html_iframe: ^3.0.0-beta.2
  html: ^0.15.4
  parchment: ^1.9.0
  html_unescape: ^2.0.0
  
  # Others
  scroll_to_index: ^3.0.1
  # sentry_flutter: ^8.1.0
  sticky_infinite_list: ^4.0.1
  vsc_quill_delta_to_html: ^1.0.3
  webview_flutter: ^4.4.1
  kalender: ^0.4.1
  desktop_webview_window: ^0.2.3
  google_generative_ai: ^0.4.6

  # Plugins
  #flutter_app_badger
  open_file_plus: ^3.4.1+1
  app_links: ^6.3.2
  # awesome_notifications: ^0.10.0
  file_picker: ^8.0.0+1
  share_handler: ^0.0.22
  share_plus: ^10.0.2
  home_widget: 
    git: 
      url: https://github.com/DiscipulusApp/home_widget.git
      path: packages/home_widget/
     
  super_drag_and_drop: ^0.8.11
  super_context_menu: ^0.8.16
  flutter_apple_spotlight: 
    git:
      url: https://github.com/DiscipulusApp/flutter_apple_spotlight.git
    # path: /Users/donda/Documents/Git/Repos/flutter_apple_spotlight/
  flutter_apple_handoff: 
    git:
      url: https://github.com/DiscipulusApp/flutter_apple_handoff.git
    # path: /Users/donda/Documents/Git/Repos/flutter_apple_handoff/
  dnd_manager: 
    git:
      url: https://github.com/DiscipulusApp/dnd_manager.git
    # path: /Users/donda/Documents/Git/Repos/dnd_manager/
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  widgets_to_image: ^1.0.0
  connectivity_plus: ^6.0.3
  android_alarm_manager_plus: ^4.0.4
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  image_picker: ^1.1.2

  # Unused
  # flutter_carousel_widget: ^2.2.0
  # flutter_sticky_header: ^0.6.5
  # go_router: ^12.1.3
  # json_annotation: ^4.8.1
  # uni_links: ^0.5.1
  # uni_links_desktop: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: Discipulus
  publisher_display_name: HarryDeKat
  identity_name: dev.harrydekat.discipulus
  msix_version: 0.0.12
  logo_path: query_stats.svg
  capabilities: internetClient
  execution_alias: m6loapp
